name: graalvm
grade: stable
version: '22.1.0-17'
summary: GraalVM java 17 for ubuntu/debian
base: bare 
build-base: core18
confinement: strict
description: |
  Coming from https://github.com/ozkanpakdil/graalvm-ce-deb/
  Source https://github.com/oracle/graal.
architectures:
  - build-on: amd64
  # - build-on: m1
  - build-on: arm64

parts:
  graalvm:
    plugin: dump
    source:
      - on amd64: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-linux-amd64-22.1.0.tar.gz
      # - on m1: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-darwin-aarch64-22.1.0.tar.gz
      - on arm64: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-linux-aarch64-22.1.0.tar.gz
    stage-packages:
      - java-common
    build-packages:
      - software-properties-common
