name: graalvm
version: '22.1.0-17'
summary: GraalVM java 17 for ubuntu/debian
description: |
  Coming from https://github.com/ozkanpakdil/graalvm-ce-deb/
  Source https://github.com/oracle/graal.
architectures:
  - build-on: amd64
    run-on: amd64
    
grade: stable
confinement: classic

parts:
  graalvm:
    plugin: nil
    build-packages:
      - software-properties-common
    override-prime: |
      snapcraftctl prime
      snap set system proxy.http=""
      snap set system proxy.https=""
      apt-get install wget
      apt install -y java-common
      wget https://github.com/ozkanpakdil/graalvm-ce-deb/releases/download/21/graalvm-ce-java17_amd64_22.1.0-0.deb
      dpkg -i graalvm-ce-java17_amd64_22.1.0-0.deb
      update-java-alternatives --set /usr/lib/jvm/graalvm-ce-java17/
      gu install native-image
      java -version
