name: graalvm
version: '22.1.0-17'
summary: GraalVM java 17 for ubuntu/debian
description: |
  Coming from https://github.com/ozkanpakdil/graalvm-ce-deb/
  Source https://github.com/oracle/graal.

grade: stable
confinement: classic

parts:
  gnome:
    plugin: nil
    source: https://apache.bintray.com/couchdb-deb/pool/C/CouchDB/couchdb_3.1.1~focal_amd64.deb
    source-type: deb
    build-packages:
      - software-properties-common
    override-pull: |
      update-java-alternatives --set /usr/lib/jvm/graalvm-ce-java17/
      gu install native-image
      java -version
