name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate release tag
      id: tag
      run: |
        rm -rf graalvm-ce-java*
        sudo apt -y install alien build-essential fakeroot devscripts debsigs
        VERSION=${{github.run_number}}
        echo "::set-output name=release_tag::$VERSION"
    - uses: actions/checkout@v3
    
    - name: build graal deb 11
      run: |
        set -x
        mkdir -p ~/.gnupg/
        echo use-agent >> ~/.gnupg/gpg.conf
        echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
        echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
        echo RELOADAGENT | gpg-connect-agent
        cat >kspecs <<EOF
         %echo Generating a OpenPGP key for GraalVM
         Key-Type: RSA
         Key-Length: 4096
         Subkey-Type: RSA
         Subkey-Length: 4096
         Name-Real: GraalVM
         Name-Comment: Graalvm key
         Name-Email: no@email.com
         Expire-Date: 0
         Passphrase: secret
         # Do a commit here, so that we can later print "done" :-)
         %commit
         %echo done
        EOF
        gpg --batch --generate-key kspecs
        gpg --list-keys
        ./build 11
    
    - name: build graal deb 17
      run: ./build 17

    - name: create rpms
      run: |
        DEBFILE=`find -name '*.deb'`
        sudo alien --nopatch -rk $DEBFILE
        
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.deb
          *.rpm
        tag_name: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
