name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate release tag
      id: tag
      run: |
        gpg --batch --pinentry-mode loopback --passphrase "" --full-generate-key generate-key
        rm -rf graalvm-ce-java*
        sudo apt -y install alien build-essential fakeroot devscripts debsigs
        VERSION=${{github.run_number}}
        echo "::set-output name=release_tag::$VERSION"
    - uses: actions/checkout@v3
    
    - name: build graal deb 11
      run: ./build 11
    
    - name: build graal deb 17
      run: ./build 17

    - name: create rpms
      run: |
        DEBFILE=`find -name '*.deb'`
        sudo alien --nopatch -rk $DEBFILE
        mv $DEBFILE .
        
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.deb
          *.rpm
        tag_name: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
